kubernetes-csi/csi-release-tools

prow.sh

Whether a component supports sanity testing depends on the
component. For example, csi-driver-host-path enables it because it
makes sense there (and only there). Letting the prow.sh script decide
whether it actually runs simplifies the job definitions in test-infra.

prow.sh: skip sanity testing if component doesn't support it

---

prow.sh

Adds necessary flags for enabling for hostpath expansion tests
/sig storage
cc @msau42

Enable hostpath expansion

---

prow.sh

Tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/100

Add new variables for 1.16 and remove 1.13

---

prow.sh

Update prow hostpath driver version from `v1.2.0` to `v1.3.0-rc2`.
```release-note
NONE
```

Update prow hostpath driver version to 1.3.0-rc2

---

prow.sh

Update snapshotter to version v2.0.0

---

prow.sh

Testing in https://github.com/kubernetes-csi/livenessprobe/pull/59

Update hostpath driver version to get fix for connection-timeout

---

SIDECAR_RELEASE_PROCESS.md

Fixes: https://github.com/kubernetes-csi/docs/issues/142

Document the process for releasing a new sidecar

---

README.md

fix incorrect link

---

prow.sh

Signed-off-by: Grant Griffiths <grant@portworx.com>

Update snapshotter to version 2.0.1

---

prow.sh

Checking out the Kubernetes source code only supported
branches (master, release-1.20) but not a version (like 1.20.0)
because tags need a leading "v". "git clone --branch" (despite the
name) is able to fetch a tag.

prow.sh: support building Kubernetes for a specific version

---

boilerplate/boilerplate.py

add csi-release-tools to the program and do verify boilerplate does not work, because default boilerplate dir error.

fix: default boilerplate path

---

go-get-kubernetes.sh

go-get-kubernetes.sh should not add all Kubernetes libraries to `replace` section, only those that are actually used.
I am not sure if it can work in all cases, comment `The presence of a potentially incomplete go.mod file affects [go mod] command` just below is a bit scary. However, it helped when rebasing an existing sidecar to a new version - it pruned all the unused libs from `replace`.
```release-note
Updated go-get-kubernetes.sh to remove unused k8s libraries from go.mod
```

go-get-kubernetes.sh: remove unused k8s libs

---

verify-shellcheck.sh

Replace `which` command ( non standard)  with `command -v` builtin

---

SIDECAR_RELEASE_PROCESS.md
cloudbuild.yaml

Needed by https://github.com/kubernetes/k8s.io/issues/1597
/kind cleanup

Master to main cleanup

---

SIDECAR_RELEASE_PROCESS.md

SIDECAR_RELEASE_PROCESS.md: add troubleshooting for image publishing

---

prow.sh

Correct prow.sh typo and make codespell linter pass

---

KUBERNETES_CSI_OWNERS_ALIASES

This PR is in reference to issue [https://github.com/kubernetes/community/issues/6334](https://github.com/kubernetes/community/issues/6334)

Fix OWNERS files with allowed keywords

---

SIDECAR_RELEASE_PROCESS.md

What type of PR is this?
/kind documentation

SIDECAR_RELEASE_PROCESS.md: Update release-notes syntax

---

prow.sh

Update to Kind v0.14.0 images:
https://github.com/kubernetes-sigs/kind/releases/tag/v0.14.0

Update to Kind v0.14.0 images

---

KUBERNETES_CSI_OWNERS_ALIASES

Would like to make active contributions to reviewing PRs as well.

Add RaunakShah to CSI reviewers group

---

prow.sh

Refer to https://github.com/kubernetes/kubernetes/blob/master/.go-version

Update go version to 1.20 to match k/k v1.27

---

prow.sh

Adopt kubernetes recommand label
```release-note
ref: https://github.com/kubernetes-csi/external-snapshotter/pull/844
```

chore: adopt kubernetes recommand label

---

SIDECAR_RELEASE_PROCESS.md

What type of PR is this?
/kind documentation
Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/test-infra/issues/30370

fixed broken links of testgrid dashboard

---

prow.sh

Refer to https://github.com/kubernetes/kubernetes/blob/master/.go-version
```release-note
Update go version to 1.21
```

Update go version to 1.21 to match k/k

---

KUBERNETES_CSI_OWNERS_ALIASES

Hi sig storage team, I have been contributing to the Kubernetes community for quite a long time(no doubt will continue longer), and learned a lot from all of your folks, thanks so much.
I want to nominate myself as a member of the reviewer team, it's not only a honor but also a kind of responsibility to me.
Reviewer requirements:
- member for at least 3 months: REQUEST: New membership for carlory [org#4254](https://github.com/kubernetes/org/pull/4254)
- Primary reviewer for at least 5 PRs to the codebase: Reviewed [10 Merged PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+-author%3Acarlory+is%3Amerged+label%3Asig%2Fstorage+reviewed-by%3Acarlory+)
- Reviewed or merged at least 20 substantial PRs to the codebase: [Merged 17 …

nominate self (carlory) as kubernetes-csi reviewer

---

prow.sh

Change go version to 1.21.5

---

SIDECAR_RELEASE_PROCESS.md
generate-patch-release-notes.sh
go-modules-targeted-update.sh

Added a script to update specific go modules, and fixed the release notes script to not depend on discover mode which seems to be broken.

Scripts for patch releases

---

.github/dependabot.yaml
.github/workflows/codespell.yml
.github/workflows/trivy.yaml

**What this PR does / why we need it**:
Added codespell for spell checking and trivy for vulnerability scanning to the csi-release-tools repository.
Currently, other CSI Sidecar repositories have spell checks and vulnerability scans using tools like codespell and trivy. However, the csi-release-tools repository lacks these configurations, which means it cannot detect spelling issues or vulnerabilities caused by the Go version within csi-release-tools.
As a result, errors like the following have been encountered:
- https://github.com/kubernetes-csi/csi-release-tools/pull/253
- https://github.com/kubernetes-csi/livenessprobe/pull/262#issuecomment-2104868664
```release-note
NONE
```
**act check**:
**codespell check**
```
[codespell/Check for …
```

Add GitHub Actions workflows

---

generate-patch-release-notes.sh

Missing release-notes tool as requirement.
```release-note
NONE
```

Instruction update

---

prow.sh

Updating release tools similar to:
https://github.com/kubernetes-csi/csi-test/pull/431
for:
https://github.com/kubernetes-csi/csi-test/pull/560

chore: update CSI driver version to 1.15

---

prow.sh

5.3.1 is the latest version.
```release-note
NONE
```

Bump csi-sanity to 5.3.1

---

KUBERNETES_CSI_OWNERS_ALIASES

I haven't participated in this org for a while.

Remove chrishenzie from kubernetes-csi-reviewers

---

prow.sh

/kind feature
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
```release-note
Updating CSI prow driver version to v1.17.0
```

Update CSI prow driver version to v1.17.0
