kubernetes-csi/csi-release-tools

README.md

Copy-and-paste error from the time when the
kubernetes-csi/csi-release-tools repo didn't have the code...

README.md: fix repo URL for initial setup

---

build.make
travis.yml
verify-subtree.sh

This adds a check that prevents modifying the "release-tools" directory in sidecar repos.
Tested and discussed here: https://github.com/kubernetes-csi/external-attacher/pull/109#discussion_r250037619
/assign @msau42

check subtree for changes

---

build.make

After merging into external-attacher, the next Travis CI run did not
push the "canary" image because the check for "canary" only covered
the case where "-canary" is used as
suffix (https://travis-ci.org/kubernetes-csi/external-attacher/builds/484095261).
/assign @msau42

build.make: fix pushing of "canary" image from master branch

---

build.make

These changes were originally tested in https://github.com/kubernetes-csi/csi-test/pull/156 and are needed for using csi-release-tools in the kubernetes-csi/csi-test repo.

test enhancements

---

verify-subtree.sh

If for whatever reasons a repo already had a `release-tools` directory
before doing a clean import of it with `git subtree`, the check used
to fail because it found those old commits.
This can be fixed by telling `git log` to stop when the directory
disappears from the repo. There has to be a commit with removes the
old content, because otherwise `git subtree add` doesn't work.
Fixes: https://github.com/kubernetes-csi/external-resizer/issues/21

verify-subtree.sh: relax check and ignore old content

---

build.make
travis.yml

This runs "dep check" to verify that the vendor directory is
up-to-date and meets expectations (= done with dep >= 0.5.0).

check vendor directory

---

build.make

In repos that have a test/e2e, that test suite should be run
separately because it depends on a running cluster.

build.make: avoid unit-testing E2E test suite

---

build.make
prow.sh

This is related to https://github.com/kubernetes/test-infra/pull/12088 but both can be merged independently.
/assign @msau42

prow enhancements

---

prow.sh

This was already meant to be done earlier in cda2fc5874b42ed68b.
While at it, extend the permanent TODO with guidance on future feature
gates.

prow.sh: remove AllAlpha=all, part II

---

build.make

I've got following error message while executed the `make test` command:
> Using shellcheck 0.6.0 docker image.
> Congratulations! All shell files are passing lint.
> /bin/sh: line 0: return: can only `return' from a function or sourced script
> make: *** [test-shellcheck] Error 1
The root cause is the test-shellcheck section in the build.make file should use `exit` command to return status code, instead of using `return`.

build.make: Replace 'return' to 'exit' to fix shellcheck error

---

prow.sh

This pulls in
https://github.com/kubernetes-csi/csi-driver-host-path/pull/37, which
turned out to be necessary for pre-submit testing of the
livenessprobe.

prow.sh: update csi-driver-host-path

---

travis.yml

Kubernetes also requires 1.12. We pick the latest stable release
for CI builds.

update to Go 1.12.4

---

build.make

How a repo does vendoring is detected based on the presence of
Gopkg.toml.
The vendor check with `dep` was all done locally, but the
corresponding check for `go mod` requires network access. The check
therefore gets skipped when running in the Prow CI in situations where
we are sure that it isn't needed (for example, in a periodic job).
This is required for https://github.com/kubernetes-csi/csi-test/pull/188
```release-note
allow vendoring with 'go mod'
```
/kind feature

build.make: allow repos to use 'go mod' for vendoring

---

prow.sh

This was tested in and is needed for https://github.com/kubernetes-csi/csi-driver-host-path/pull/64.
/assign @msau42 
```release-notes
NONE
```

more flexible test driver config

---

prow.sh

Updates prow.sh to use 1.15 hostpath deployment. As a result, the kind version also has to be upgraded to 0.4.0, which requires 2 major changes to our prow job:
* We need to use the new `kind.sigs.k8s.io/v1alpha3 Cluster` API object, which uses `kubeadm.k8s.io/v1beta2` which only works for 1.15+. As a result, our alpha jobs can only run on 1.15+
* kind 0.4.0 supports very specific patch images of 1.15, 1.14, 1.13, etc, which are not the ones we have configured in our prow jobs. As a result, I have added logic in the prow job to override the patch versions.
Also updates the config so that sidecar testing uses the version of the hostpath repo at v1.2.0-rc2.
```release-notes
Update kind to 0.4.0 to be able to run 1.15 jobs.
Fixes sidecar testing to use stable hostpath images.
```

Add 1.15 jobs

---

prow.sh

kind [checks kubernetes tagged versions](https://github.com/kubernetes-sigs/kind/blob/9205bac4a8377fb7d301a8c14650592b85a34f58/pkg/cluster/internal/kubeadm/config.go#L451-L459) to figure out which config to use. For master builds, tag a large version so that kind will look for the latest config versions.
Tested master alpha clusters in https://github.com/kubernetes-csi/csi-driver-host-path/pull/74
```release-notes
Tag master binaries with v999.999.999 so that kind will use the latest kubeadm config
```

prow.sh: tag master images with a large version number

---

prow.sh

Kubernetes master changed the way that versions are determined, which requires a new kind build.
This PR has 3 changes:
1. Use a master commit of kind that includes the fix for Kubernetes
master.
2. Use git clone instead of git checkout (shallow) to source Kubernetes.
This lets kind correctly figure out the Kubernetes release tag.
3. Build kind with make install. The kind fix was not working correctly
when built with go build.
This has been tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/77

Fix CI jobs on Kubernetes master

---

prow.sh

"make test-vendor" depends on dep if the current project uses
dep. Without it, the vendor directory checking was skipped under Prow.
/release-notes-none

prow.sh: install dep if needed

---

prow.sh

Create 2-node kind cluster since topology support is added to hostpath
Tested with https://github.com/kubernetes-csi/csi-driver-host-path/pull/92
Fixes #28
/release-notes-none
cc @msau42

Create 2-node kind cluster since topology support is added to hostpath

---

build.make

so that it doesn't override linux binary

build windows binaries with .exe suffix

---

build.make

Skip with trying to build CSI binaries for Windows OS in non amd64 arch. Addresses https://github.com/kubernetes-csi/external-attacher/issues/185#issuecomment-538949667
This is just a short term fix. I think long term we should specify a matrix of supported OS/ARCH combos as is done in [k/k](https://github.com/kubernetes/kubernetes/blob/886af6aa26fd82d495931129863cd98ac21ea90e/build/root/.bazelrc#L33-L46)

Build Windows only for amd64

---

README.md
build.make
go-get-kubernetes.sh

It turned out that changes like
https://github.com/kubernetes-csi/csi-lib-utils/pull/33 should better
have been committed after `go mod tidy` because that adds some
indirect dependencies in that example.
The revised `test-vendor` checks for that and (just in case that this
ever becomes desired) allows projects to not have a vendor directory
when using `go mod`.
How to use `go mod` properly gets documented in the README.md, because
there are such pitfalls.

update Go mod support

---

build.make
travis.yml
update-vendor.sh
verify-go-version.sh
verify-vendor.sh

This bumps the version of Go to the latest one, adds a version check and a helper script for vendoring.

Go version 1.13, helper scripts

---

build.make
prow.sh
travis.yml

This avoids dependencies on the Go module cache or the upstream code
hosting. This had been discussed before, but then was left out of PR #41 
unintentionally.

prow.sh: use vendor directory if available

---

prow.sh

Depending on the error, those logs are needed to debug failures.
Fixes: #31

prow.sh: also log output of system containers

---

prow.sh

Delete kind cluster after tests run. Inside a real Prow job it is better to clean up at runtime instead of leaving that to the Prow job cleanup code because the later sometimes times out.
Tested with the PR: https://github.com/kubernetes-csi/csi-driver-host-path/pull/120
Fixes: https://github.com/kubernetes-csi/csi-release-tools/issues/24
cc @msau42 @pohly

delete kind cluster after tests run

---

prow.sh

```release-notes
Adds snapshotter CRDs after cluster setup
```
Changes required for https://github.com/kubernetes-csi/csi-driver-host-path/pull/98
Signed-off-by: Grant Griffiths <grant@portworx.com>

Add snapshotter CRDs after cluster setup

---

build.make

This PR adds builds for ppc64le.
```release-note
Cross build binaries for ppc64le
```
A relevant issue for discussion has been put here: https://github.com/kubernetes-csi/csi-release-tools/issues/48

Adding build for ppc64le

---

prow.sh

kind v0.6.0 appends the kubeconfig with the default config at
`~/.kube/config`.
Fixes #39 
```release-note
NONE
```

Use kind v0.6.0

---

prow.sh

```release-notes
NONE
```
Signed-off-by: Grant Griffiths <grant@portworx.com>

Improve snapshot-controller running check and version_gt to support multiple formats 

---

prow.sh

Tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/129/files
This requires adding one more parallel e2e test run with
a special focus flag because snapshot tests are still guarded
with a "[Feature:VolumeSnapshotDataSource]" tag. The setting that
skips all tests with "[Feature:.*]" has to be removed because it
overrides the focus.
We don't have serial snapshot tests yet. This needs to be modified
again if we add any in the future.

Enable snapshot tests in 1.17 to be run in non-alpha jobs.

---

prow.sh

Keeping this function in sync with the hostpath version.
https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/deploy/util/deploy-hostpath.sh#L104
Signed-off-by: Grant Griffiths <grant@portworx.com>

Fix version_gt to work with Kubernetes prefix

---

prow.sh

That this hasn't been done before is an oversight. Apparently it
hasn't been a problem because there never have been feature gates that
mattered?

prow.sh: also configure feature gates for kubelet

---

prow.sh

This relies on a slightly different deployment script: a "deploy.sh"
must exist which knows that it has to dump a test driver configurion
into the file pointed to with CSI_PROW_TEST_DRIVER, if that env
variable is set.
That way, we no longer need to know what capabilities the installed
driver has.
The corresponding change in the hostpath repo is in https://github.com/kubernetes-csi/csi-driver-host-path/pull/143

prow.sh: generic driver installation

---

build.make

It feels to me like `make test-vet` was supposed to call `go vet` and not `go test` because that is already done in `make test-go` (extra excluding e2e directory, but still very similar).
Not sure if it was intentional or by accident in https://github.com/kubernetes-csi/csi-release-tools/pull/42
ptal: @pohly @msau42

Change 'make test-vet' back to call 'go vet'

---

prow.sh

The final 1.3.0 release of the hostpath driver really uses the 1.3.0
driver image in its deployment, in contrast to the previous -rc
candidates which still used 1.2.0.

prow.sh: use 1.3.0 hostpath driver for testing

---

build.make
prow.sh

Developers should not be forced to build for all platforms by
default. We also don't want to copy-and-paste the go invocation for
each new platform.
To address both, the target platform(s) are now configurable via
BUILD_PLATFORMS and additional platforms are only enabled in the Prow
CI.
For now this serves as a test that the source actually compiles for
multiple platforms. Building images for different target platforms is a
different problem.

build for multiple platforms only in CI, add s390x

---

SIDECAR_RELEASE_PROCESS.md

I updated to the latest release tools. There are some new options that help reduce the toil of finding the right commit hashes. The new "patch-to-patch" discover mode doesn't work for our patch release model, but I may spend some time trying to add one that works for us.
Here's a sample release notes format that gets generated. We'll still need to do some post modifications to the title and documentation link, but the rest seems ok.
```
[Documentation](https://docs.k8s.io/docs/home)
- Users can now provide a secret name and namespace during provision by passing the correct storage class parameters: "provisioner-secret-name" and "provisioner-secret-namespace" ([#286](https://github.com/kubernetes-csi/external-provisioner/pull/286), [@oleksiys](https://github.com/oleksiys))
- A new flag …
```

update release tools instructions

---

prow.sh

Caught in this PR:
https://github.com/kubernetes-csi/external-snapshotter/pull/298
Testing this change in this PR:
https://github.com/kubernetes-csi/external-snapshotter/pull/299

Fix csi-snapshotter RBAC yaml version

---

SIDECAR_RELEASE_PROCESS.md

Currently this requires a custom built version of the release notes tool off of head. Hopefully 2.8 will be released soon.

Update patch release notes generation command

---

build.make
cloudbuild.sh
cloudbuild.yaml
prow.sh

The approach taken here extends the existing support for
cross-compiling binaries on the build host and specifying the Go
compiler: Go is installed if needed (as in Prow testing), binaries are
build on the host, then one image is created for each platform, and
finally those are combined into a single multi-architecture image.
```release-note
The Dockerfile must accept a "binary" build argument.
```

cloud build: initial set of shared files

---

build.make

Several of the cloud build jobs (https://testgrid.k8s.io/sig-storage-image-build) are currently broken because the missing Dockerfile.Windows. The push-multiarch ambiguity was found when testing the updated build.make in different repos.

multiarch windows fix

---

prow.sh

If the Dockerfile needs to run some command, that step fails unless
QEMU is set up properly first:
failed to solve: rpc error: code = Unknown desc = failed to load
LLB: runtime execution on platform linux/ppc64le not supported
/cc @jsafrane

cloud build: initialize support for running commands in Dockerfile

---

cloudbuild.yaml

As discussed in https://github.com/kubernetes/k8s.io/pull/943, we want
to consolidate under k8s-staging-sig-storage.

cloud build: k8s-staging-sig-storage

---

prow.sh

Add linux/arm64 architecture to prow build platforms.

prow.sh: enable building arm64 image

---

filter-junit.go

Signed-off-by: Animesh Kumar <animuz111@gmail.com>
This commit is aimed to fix the golint error for this PR: https://github.com/kubernetes-csi/csi-driver-smb/pull/28
The build log can be found here: https://travis-ci.org/github/kubernetes-csi/csi-driver-smb/builds/699003032#L532

filter-junit: Fix golint error

---

filter-junit.go

Signed-off-by: Animesh Kumar <animuz111@gmail.com>
This commit is aimed to fix the gofmt error in this PR: https://github.com/kubernetes-csi/csi-driver-smb/pull/28
Build log can be found here: https://travis-ci.org/github/kubernetes-csi/csi-driver-smb/builds/699596732#L505

filter-junit: Fix gofmt error

---

cloudbuild.yaml

The recent [post-external-snapshotter-push-images](post-external-snapshotter-push-images) builds have been failing due to [timeout](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-external-snapshotter-push-images/1280665205386252288). 
Snippet from log:
```
go: finding github.com/prometheus/common v0.4.1
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
+ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -ldflags '-X main.version=v2.1.0-57-g097b1fc7 -extldflags "-static"' -o ./bin/csi-snapshotter.exe ./cmd/csi-snapshotter
+ CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -a -ldflags '-X main.version=v2.1.0-57-g097b1fc7 -extldflags "-static"' -o ./bin/csi-snapshotter-ppc64le ./cmd/csi-snapshotter
+ CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -a -ldflags '-X …
```

cloud build: bump timeout in Prow job

---

SIDECAR_RELEASE_PROCESS.md

/assign @jsafrane @gnufied @xing-yang @pohly

Add steps on promoting release images

---

travis.yml

Go 1.15 was released and is the major version that Kubernetes 1.19.0
is going to use. There are probably bugs in the older 1.13.3 that were
fixed, so we should update.

switch to Go 1.15

---

prow.sh

This fixes the "kubernetes-1-18-on-1-18" jobs and jobs against Kubernetes master.

Kubernetes 1.19 fixes

---

prow.sh

Fixes: #102 
/kind failing-test
Testing in https://github.com/kubernetes-csi/csi-driver-host-path/pull/202

Use staging registry for canary tests

---

SIDECAR_RELEASE_PROCESS.md

Update release process

---

prow.sh

This PR updates snapshot-controller image to 3.0.0.

Update to snapshot-controller v3.0.0

---

prow.sh

/kind cleanup
**What this PR does / why we need it**:
The new kind release adds support for recent Kubernetes releases like 1.19 and
simplifies configuration of feature gates.
With Kubernetes 1.19, new feature gates were introduced which might
become relevant for the alpha Prow jobs.
```release-note
kind updated to 0.9, Kubernetes 1.19 supported
```

prow.sh: update to kind 0.9, support Kubernetes 1.19

---

build.make

What type of PR is this?
/kind bug
What this PR does / why we need it:
This PR allows adding ldflags while running make. We are trying to build binaries without debug info. With this change we will be able to pass -s flag as an argument to Makefile.
```release-note
Add go ldflags using LDFLAGS at the time of compilation.
```

Add go ldflags using LDFLAGS at the time of compilation

---

prow.sh

Kind 0.9.0 accesses the "bazel-out" directory with a relative path,
which only works when the command is invoked inside the Kubernetes
source code
directory (https://github.com/kubernetes-sigs/kind/issues/1910).

prow.sh: work around "kind build node-image" failure

---

prow.sh

Commit 7bcee13d79012 added alpha feature gates for Kubernetes 1.19 in
the CSI_PROW_E2E_ALPHA_GATES_LATEST variable based on the comment in
https://github.com/kubernetes-csi/external-provisioner/pull/493#discussion_r502663402
that alpha testing only runs for the latest Kubernetes.
But some components (like external-health-monitor) are configured with
a single Prow job which runs the default set of tests on a stable
Kubernetes release (currently 1.17). Those tests used to include alpha
testing which then broke during Kind cluster startup because the
Kubernetes 1.19 feature gates weren't recognized by 1.17.
The solution is to disable alpha testing for Kubernetes != latest in
the default set of tests.

prow.sh: only run alpha tests for latest Kubernetes release

---

prow.sh

This PR installs snapshot CRDs and rbac rules from the repo
and installs snapshot controller from a local image if it is
a PR in external-snapshotter repo.
Otherwise it uses main or a stable version.

Fix the install of snapshot CRDs and controller

---

cloudbuild.yaml

Builds of external-snapshotter sometimes timed out because it builds
three images and that takes almost half an hour (the previous limit)
and more if the network is slow.
There's no good way to set timeouts per repo and a too high timeout
for shouldn't cause any issue, therefore the timeout gets increased
everywhere.
/cc @xing-yang

cloud build: double the timeout, now 1 hour

---

prow.sh

The current csi-test version doesn't support the new capabilities, like VOLUME_CONDITION and GET_VOLUME. Both of them are needed by the external-health-monitor project and other projects which are integrating with external-health-monitor: https://github.com/kubernetes-csi/csi-driver-host-path/pull/210.
In that case, I think we need to upgrade the version of csi-test
```release-note
upgrade version of csi-test to v4.0.2
```

upgrade csi-test to v4.0.2

---

boilerplate/boilerplate.Dockerfile.txt
boilerplate/boilerplate.Makefile.txt
boilerplate/boilerplate.bzl.txt
boilerplate/boilerplate.go.txt
boilerplate/boilerplate.py
boilerplate/boilerplate.py.txt
boilerplate/boilerplate.sh.txt
build.make
verify-boilerplate.sh
verify-spelling.sh

The `verify-spelling.sh` and `verify-boilerplate.sh` (and its tests scripts in `boilerplate`) are added to enable checks for common typos and checking the boilerplates of the files. It is required to fix [#128](https://github.com/kubernetes-csi/csi-driver-nfs/issues/128) in https://github.com/kubernetes-csi/csi-driver-nfs.
Also fixes #58 
```release-note
Added checks for spellings and boilerplates in the files.
```
/cc @pohly @msau42

Add spelling and boilerplate checks

---

.prow.sh
SIDECAR_RELEASE_PROCESS.md
cloudbuild.sh
prow.sh
verify-boilerplate.sh
verify-spelling.sh
verify-subtree.sh

Some spelling and boilerplate errors are fixed which caused the failure of these tests.
Fixes #123

Fix spelling and boilerplate errors

---

build.make
verify-boilerplate.sh
verify-spelling.sh

The boilerplate and spelling tests are made optional and the default paths in the relative scripts are made absolute.
This is in response to the discussion [here](https://github.com/kubernetes-csi/csi-driver-nfs/pull/133#discussion_r556036984) for the PR ![#133](https://github.com/kubernetes-csi/csi-driver-nfs/pull/133)

Make the spelling and boilerplate checks optional

---

verify-boilerplate.sh

The previous path was wrong because it was relative to the directory
being checked, not the release-tools directory:
```
csi-driver-host-path$ ./release-tools/verify-boilerplate.sh
Verifying boilerplate
./release-tools/verify-boilerplate.sh: line 37: /nvme/gopath/src/github.com/kubernetes-csi/csi-driver-host-path/boilerplate/boilerplate.py: No such file or directory
```

verify-boilerplate.sh: fix path to script

---

prow.sh

```release-note
None
```
For two issues:
1. there is no test file under /csi-test/cmd/csi-sanity in v4.0.2 version. It was old code in v2.2.0. In that case, we should use go test -c to build binary file of csi-sanity https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/release-tools/prow.sh#L883
2. fetch csi-test from upstream always

fix: fix a bug of building csi-sanity

---

prow.sh

This PR adds additional check for namespace specified in manifest for snapshot-controller
needed for https://github.com/kubernetes-csi/external-snapshotter/pull/459#issuecomment-750934403
```release-note
Check namespace for snapshot-controller tests
```

Check namespace for snapshot-controller

---

prow.sh

The recent introduction of version_to_git broke Prow jobs with
CSI_PROW_KUBERNETES_VERSION=latest because that version was first
converted to "master" and then once more to "vmaster". The second call
must be idempotent because "master" is already a branch name.

prow.sh: fix "on-master" prow jobs

---

build.make

this PR is for https://github.com/kubernetes-csi/csi-driver-nfs/pull/166 to build multi-arch images
original error:
```
#7 [3/3] RUN apt update && apt install ca-certificates mount nfs-common nfs...
#7 0.115 /bin/sh: Invalid ELF image for this architecture
#7 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c apt update && apt install ca-certificates mount nfs-common nfs-kernel-server -y || true]: exit code: 255
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-csi-driver-nfs-push-images/1363278699297771520
```release-note
none
```

add build-arg ARCH

---

verify-go-version.sh

Two problems:
- sourcing prow.sh prints info messages about settings which should
better be suppressed
- the expected value was hidden by the incorrect make-style quoting
of CSI_PROW_GO_VERSION_BUILD

verify-go-version.sh: fix check after removal of travis.yml

---

prow.sh

The new release adds a pre-built image for Kubernetes 1.20.2.

prow.sh: KinD 0.10.0

---

prow.sh

KinD 0.10.0 fails to bring up a Kubernetes cluster for the latest (>
1.21.0-beta1) sources. Such breakage is expected and will be dealt
with on the main branch of KinD. Therefore we should always use when
building a cluster from source code. We have been lucky in the past
that the released versions of KinD also happend to support the latest
Kubernetes.
The downside is that temporary regressions in KinD will also affect
the Prow jobs that use the latest Kubernetes, but this is not new and
could also have happened because of regressions in Kubernetes.
While at it, building KinD gets fixed to use the configured Go
version. It happened to use Go from the default PATH.
The most recent KinD no longer supports the --type parameter, so we
have to filter that out when using KinD main.

prow.sh: use KinD main for latest Kubernetes

---

prow.sh

verify-go-version.sh sources prow.sh to determine the desired Go
version. This had the unintended side effect of creating one
$GOPATH/pkg/csiprow.* directory per make invocation and triggered
error messages when GOPATH was not set.
Also, `go env GOPATH` is now used as fallback when not set explicitly.
Fixes: https://github.com/kubernetes-csi/csi-release-tools/issues/142

prow.sh: avoid creating paths unless really running tests

---

pull-test.sh

This will be used by special Prow pull
jobs (https://github.com/kubernetes/test-infra/pull/21995) to ensure
that an update of csi-release-tools works in consuming repos.

pull-test.sh: test importing csi-release-tools into other repo

---

prow.sh

This adds support for the new Kubernetes 1.21 jobs (currently enabled, but not required) and for testing different deployment variants (pending in https://github.com/kubernetes-csi/csi-driver-host-path/pull/282).

Kubernetes 1.21

---

prow.sh

We already run the e2e.test binary from Kubernetes in different
invocations (serial, parallel, with and without alpha
features). Enabling also the in-tree mock tests is therefore easy and
makes sense in particular for our canary jobs where we try out how our
canary images work in existing deployments before updating those
deployments.
To role this out:
- merge this PR
- update csi-driver-host-path
We don't need to update jobs because the default is to include mock tests when
canary images are enabled.

Mock testing

---

prow.sh

This enables the -csi.checkpathcmd option, which is needed in order
to test if TargetPath was successfully removed by the CSI driver as
part of NodeUnpublishVolume.
This is a follow up to https://github.com/kubernetes-csi/csi-test/pull/338
cc: @gnufied @pohly

prow.sh: enable -csi.checkpathcmd option in csi-sanity

---

build.make
cloudbuild.yaml
prow.sh

Fixes #145
Adds new parameters in BUILD_PLATFORMS referred as `base_image` and `addon_image` with the format `image:tag`
```
make push-multiarch BUILD_PLATFORMS="linux amd64; windows amd64 .exe nanoserver:2019 servercore:2019;
```
List of changes:
- made /bin/bash the default shell instead of /bin/sh, I needed to do this to do string addition and indexOf
- updated the cloudbuild docker image to a newer version that has 20.10 and this fix: https://github.com/docker/cli/issues/2722#issuecomment-693395773
- docker build with multiple build platforms with different base images
- created a docker manifest with info about all of these builds including info about the combinations of arch, os and os-version
Output of some snippets used here:
```
build_platforms=build_platforms="linux amd64; linux …
```

Add parameter base_image and addon_image to BUILD_PLATFORMS

---

prow.sh

The recently added -csi.checkpathcmd and the associated test are
supported only by csi-test v4.2.0.

prow.sh: use csi-test v4.2.0

---

build.make

Commit bfbb6f357b9367db00aafba148aab14aa701ba38 added a sed expression
with $. $ must be escaped as $$ when embedded inside a Makefile.
This should fix:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-csi-driver-host-path-push-images/1395113250458177536
```
++ sed -e 's/windows *[^ ]* *.exe *[^ ]* *[^ ]*//g' -e 's/; *;/;/g' -e 's/;[ ]*/'
sed: unmatched '/' 
```

build.make: fix image publishng

---

prow.sh

We create at most two different clusters for each job, one with alpha
features enabled and one without. For both the logs of system
components are collected before tearing down the cluster and stored as
artifacts under "cluster-logs/[non-]alpha".
This is useful in particular for kubelet logs.
Fixes #55

prow.sh: collect cluster logs

---

KUBERNETES_CSI_OWNERS_ALIASES

I contribute and belong to owners group of csi projects as seen here (https://github.com/kubernetes-csi/csi-driver-iscsi/blob/master/OWNERS) . I would be contributing more and also helping on csi project in overall, so would like to mark my presence in reviewers group.

Adding myself to csi reviewers group

---

prow.sh

CSI_PROW_DEPLOYMENT was set explicitly for a variety of jobs. When
testing an upcoming Kubernetes release, those jobs failed because an
explicit CSI_PROW_DEPLOYMENT=kubernetes-1.21 was not matched to
kubernetes-latest and thus failed because such a deployment usually
only gets added much later.
This must have been broken for a long time.

prow.sh: more flexible CSI_PROW_DEPLOYMENT

---

prow.sh

Commit 61538bb776c5cae63d8dc40c68e6830389774c62 worked for some
jobs, but not for all, for example not for
CSI_PROW_KUBERNETES_VERSION=latest CSI_PROW_DEPLOYMENT=kubernetes-1.21
The approach taken now is to have one code path for all file checks
regardless whether CSI_PROW_DEPLOYMENT is set or not. The first
version number in the deployment name gets replaced with "latest" for
the fallback.
/assign @xing-yang

prow.sh: more flexible CSI_PROW_DEPLOYMENT, part II

---

prow.sh

The new release has pre-built images for Kubernetes 1.21, so we no
longer need to build those ourselves.

prow.sh: update to KinD v0.11.0

---

prow.sh

Mock testing was added in 74cfbc97 with the goal of increasing
test coverage and ensuring that the sidecars and driver work once
we try to use them in Kubernetes.
It turned out that this is problematic in "canary-on-<some old
Kubernetes>" jobs because those old Kubernetes version sometimes have
incompatible deployments (-provisioner argument in
external-provisioner!) because they did mock testing with much older
sidecars. Only testing against Kubernetes master is (relatively) save
and also more useful because that is where intend to use the sidecars.
Another issue was that filtering of JUnit entries did not preserve the
new mock volume entries.

prow.sh: fix mock testing

---

prow.sh

In KinD 0.11.0, --type=bazel triggers an error:
ERROR: --type is no longer supported, please remove this flag
This broke Prow jobs with CSI_PROW_KUBERNETES_VERSION=release-1.[18|19|20].

prow.sh: remove Bazel build support

---

prow.sh

This is required for distributed provisioning where the Pod name is
dynamically generated as part of the DaemonSet.

prow.sh: allow shell commands in CSI_PROW_SANITY_POD

---

README.md
SECURITY_CONTACTS
SIDECAR_RELEASE_PROCESS.md
cloudbuild.yaml
prow.sh

What this PR does / why we need it:
Needed for kubernetes/k8s.io#1597
Which issue(s) this PR fixes (optional, using fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged):
Needed for kubernetes/k8s.io#1597
---
Note that this PR only captures github links referencing master to point to HEAD instead, which will redirect to the default branch which have been master but now transitions to become main. More work needs to be done to fully transition.

docs: make github links reference HEAD instead of master

---

SIDECAR_RELEASE_PROCESS.md

Only maintainers memberhip is required to do a release

Remove requirement to be top-level approver for release

---

prow.sh

k8s has official builds for `linux/arm` platform, but csi tools do not have images for this platform. This small change fixes this. 
Related issues:
kubernetes-csi/node-driver-registrar#161.

Release armv7 images

---

prow.sh

https://k8s-testgrid.appspot.com/sig-storage-csi-ci#canary-on-master was using
the snapshot-controller from the YAML file in the master branch, which is the
latest stable release. What needs to be tested instead is the canary image to
detect regressions before a release.

prow.sh: deploy canary snapshot-controller in canary jobs

---

prow.sh

This PR adds Windows Server 2022 to the build platforms. In the future, I will sync this with the relevant subtrees

Added WS2022 to 'CSI_PROW_BUILD_PLATFORMS'

---

prow.sh

Took the versions from https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
Tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/330
/cc @pohly

Bump kind to v0.11.1

---

go-get-kubernetes.sh

Not pruning is safer because it allows adding k/k to a project at a
later time. Therefore adding all replace statements is the default.
A new flag can be used to clean up if desired. It's just a cosmetic
change because unused replace statements are ignored by Go.
/assign @jsafrane 
/cc @msau42

go-get-kubernetes.sh: make replace statement pruning optional

---

prow.sh

This changes the Go version that is going to be used when building components.
The intention is to use this for all master branches.

prow.sh: bump Go to 1.17.3

---

prow.sh

Following step 3 of https://github.com/kubernetes-csi/csi-release-tools/blob/master/SIDECAR_RELEASE_PROCESS.md#adding-support-for-a-new-kubernetes-release, similar to https://github.com/kubernetes-csi/csi-release-tools/pull/174/files
/cc @pohly

Add kind image for 1.23

---

cloudbuild.yaml

Building 3 snapshot images are taking longer than an hour recently.  As a result, it timed out before finish building the snapshot validation webhook image.  That's why we only see snapshot-controller and CSI snapshotter sidecar images in the staging repo, but not the webhook one, when cutting release v5.0.0 for external-snapshotter.
https://k8s-testgrid.appspot.com/sig-storage-image-build#post-external-snapshotter-push-images
So we need to bump the timeout value.

Increase build timeout

---

build.make
prow.sh

Adds support to build arm/v7 images:
- I added another element in the BUILD_PLATFORM tuple that's the docker buildx platform (unfortunately it's arm/v7 which is not a valid GOARCH)
- Modified other locations to use the new element `buildx_platform` in the image tag
Logs:
```
❯ make push-multiarch PULL_BASE_REF=master IMAGE_TAGS=v3.1.0-canary REGISTRY_NAME=<registry> BUILD_PLATFORMS="linux amd64 amd64; linux ppc64le ppc64le -ppc64le; linux s390x s390x -s390x; linux arm arm -arm; linux arm64 arm64 -arm64; linux arm arm/v7 -armv7; windows amd64 amd64 .exe nanoserver:1809 servercore:ltsc2019; windows amd64 amd64 .exe nanoserver:1909 servercore:1909; windows amd64 amd64 .exe nanoserver:2004 servercore:2004; windows amd64 amd64 .exe nanoserver:20H2 servercore:20H2; windows amd64 amd64 .exe …
```

Add support to build arm/v7 images

---

prow.sh

Allows for testing of the `SINGLE_NODE_MULTI_WRITER` capability.
```release-note
NONE
```
@pohly

Update csi-sanity test suite to v4.3.0

---

prow.sh

/hold
/cc @jingxu97 @pohly @andyzhangx 
Removing support for some Windows versions that have reached EOL https://endoflife.date/windows, the versions that we still maintain are ltsc2019, 20H2 and ltsc2022.
I think we could merge this in 1.24.

Remove Windows versions 1909 and 2004 which have reached EOL

---

prow.sh
verify-spelling.sh

This is the latest stable release and the one used by Kubernetes 1.24.

update to Go 1.18

---

prow.sh

https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
https://github.com/kubernetes/enhancements/pull/3079
https://github.com/kubernetes-csi/csi-driver-host-path/pull/357
/cc @pohly

Move from k8s.gcr.io to registry.k8s.io

---

prow.sh

It failed for two reasons:
- CSIDriver v1beta1 as used in csi-driver-host-path v1.3.0 is no longer
supported.
- GenericEphemeralVolume was removed in Kubernetes master.

fix testing with latest Kubernetes

---

prow.sh

Some of the CSI components may need to tweak the by default enabled
feature gates for latest clusters for their operations. This
configuration knob helps them for controlling it.
```release-note
From this release onwards, a configuration variable called `CSI_PROW_E2E_GATES_LATEST` is available for CSI components to control the feature gate configuration  for latest version of E2E clusters.
```

introduce control variable for non alpha feature gate configuration

---

filter-junit.go
prow.sh

Kubernetes 1.25 is switching to Ginkgo v2 for the e2e.test suite.
This has two implications:
- we must built a matching ginkgo binary because communication
between the ginkgo binary and library changed, affecting for
example running of parallel tests: this is done by using the
Kubernetes make rules to build the binary when using the Kubernetes
e2e.test suite
- the ginkgo v2 JUnit file is slightly different: filter-junit.go
now first tries the old format, then the new one

support Kubernetes 1.25 + Ginkgo v2

---

prow.sh

The main difference is that csi-sanity is now built with Ginkgo v2.
It should work as before.

prow.sh: sanity testing with csi-test v5.0.0

---

prow.sh

This update is necessary because the default driver
version (csi-driver-host-path v1.8.0) no longer supports Kubernetes v1.17.0 (it
needs the v1 CSIDriver API).
1.22 is the oldest supported version at this point. This matches what we are
using as base in Prow at the moment. v1.22.0 is what the current kind has
pre-built images for.

prow.sh: bump Kubernetes to v1.22.0

---

prow.sh

The right snapshotter for Kubernetes 1.22 is v4.0.0.

prow.sh: update snapshotter version

---

prow.sh

This PR adds the image for Kind 1.24.
https://github.com/kubernetes-sigs/kind/releases/tag/v0.14.0

Add 1.24 Kind image

---

prow.sh

Additional note for reviewer:
It seems to me that, this mention of 1.18 is causing the CI to fail while doing test-vendor in imported project. (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-iscsi/137/pull-kubernetes-csi-csi-driver-iscsi/1567026945609175040)
https://github.com/kubernetes-csi/csi-driver-iscsi/pull/137#issuecomment-1237703595
After having this patch in place only `test-subtree` fails in CI which is expected: (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-iscsi/137/pull-kubernetes-csi-csi-driver-iscsi/1567035242248671232)
```
./release-tools/verify-subtree.sh release-tools
Directory 'release-tools' contains non-upstream changes:
commit …
```

 release tools update to 1.19

---

prow.sh

Able to run on external-provisioner when tests are added to that repo:
```
Thu Sep 22 10:20:31 IST 2022 go1.18.3 /Users/raunakshah/go/src/src/github.com/kubernetes-csi/external-provisioner$ env KUBECONFIG=/Users/raunakshah/.kube/config KUBE_TEST_REPO_LIST= ginkgo -v -focus=Test1 /Users/raunakshah/go/src/pkg/csiprow.ProhizqqL5/e2e.test -- -report-dir /Users/raunakshah/go/src/pkg/csiprow.ProhizqqL5/artifacts
Sep 22 10:20:32.938: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
Running Suite: E2E suite - /Users/raunakshah/go/src/pkg/csiprow.ProhizqqL5
==========================================================================
Random Seed: 1663822232
Will run 1 of 1 specs
------------------------------
Test1 test1
test-1-A …
```

Changes to csi prow to run e2e tests in sidecars

---

prow.sh

Currently, no CI job has SELinux configured, so skip all tests that require it by default.. When a job supports SELinux, it can set `CSI_PROW_E2E_SKIP='Disruptive'` in its prow yaml.
Fixes: https://github.com/kubernetes-csi/csi-driver-host-path/issues/376
Needs https://github.com/kubernetes/kubernetes/pull/113809 merged first.
```release-note
NONE
```

Skip SELinux tests in CI by default

---

filter-junit.go
prow.sh

See https://kubernetes.slack.com/archives/C8EJ01Z46/p1671220069816979

JUnit fixes

---

filter-junit.go

test: fix golint error
Error: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (staticcheck)
https://github.com/andyzhangx/csi-driver-nfs/actions/runs/4354578960/jobs/7610055522

test: fix golint error

---

prow.sh

At present, the version of golang dep being checked and installed in install_dep() are inconsistent. Unify them to the actual installed version, which is v0.5.4

Fix golang dep version mismatch

---

cloudbuild.yaml

Try to fix build failures:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-external-provisioner-push-images/1650605297175105536/build-log.txt
Looks like go 1.20 added a new requirement to dynamically link to libresolv.so, and our image builder is based on alpine which doesn't support it:
https://github.com/golang/go/issues/59305

Update cloudbuild image

---

build.make

Workaround https://github.com/docker/cli/issues/3969
Build failure: https://storage.googleapis.com/kubernetes-jenkins/logs/post-external-provisioner-push-images/1650918675659624448/build-log.txt

Pin buildkit to v0.10.6 to workaround v0.11 bug with docker manifest

---

contrib/get_supported_version_csi-sidecar.py

That script is a helper to update the tables from : https://kubernetes-csi.github.io/docs/sidecar-containers.html
The next goal is to generate the tables from the release pages but... we have to agree upon the metadata and fix the typos :-) (cf. https://github.com/kubernetes-csi/external-attacher/releases with `docker pull docker pull registry.k8s.io/sig-storage/csi-attacher:v4.3.0`)

Check CSI sidecar supported versions

---

prow.sh

Changes are tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/434

Add ginkgo timeout to e2e tests to help catch any stuck tests

---

cloudbuild.yaml

Using a more recent version will address the CVE reported here : https://github.com/kubernetes-csi/external-attacher/issues/459

Update cloudbuild image with go 1.20.5

---

SIDECAR_RELEASE_PROCESS.md
cloudbuild.yaml

This PR updates the registry from k8s.gcr.io to registry.k8s.io
Issue: https://github.com/kubernetes/k8s.io/issues/4738
Ref change: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1151#discussion_r1110158081

Update registry k8s.gcr.io -> registry.k8s.io

---

contrib/get_supported_version_csi-sidecar.py

Fixing some codespell errors which are getting flagged in repos that consume these tools and have the codespell github action enabled
Ex: https://github.com/kubernetes-csi/csi-proxy/pull/289

fixing some codespell errors

---

prow.sh

remove windows 20H2 build since it's EOL more than one year ago
**Release note**:
```
remove windows 20H2 build since it's EOL long time ago
```

remove windows 20H2 build since it's EOL long time ago

---

prow.sh

Bump csi-driver-host-path version up to v1.12.0
Partial Fix: https://github.com/kubernetes/kubernetes/issues/120997

Bump csi-driver-host-path version up to v1.12.0

---

pull-test.sh

Without a prior `git reset --hard`, `git subtree pull` fails with:
fatal: working tree has modifications.  Cannot add.
Debugging with -d doesn't show any explanation and neither `git diff` nor `git diff-index` show any modifications. The `git reset --hard` shouldn't be necessary.

pull-test.sh: avoid "git subtree pull" error

---

SIDECAR_RELEASE_PROCESS.md
generate_patch_release_notes.sh

Sample PR: https://github.com/kubernetes-csi/external-provisioner/pull/1061

Add script to generate patch release notes

---

SIDECAR_RELEASE_PROCESS.md
go-modules-update.sh

A wrapper script to generate sidecar release prs from go-get-kubernetes.sh: https://github.com/kubernetes-csi/csi-release-tools/issues/7#issuecomment-707025402
- https://github.com/kubernetes-csi/external-attacher/pull/389
- https://github.com/kubernetes-csi/external-health-monitor/pull/144
- https://github.com/kubernetes-csi/external-snapshotter/pull/791
- https://github.com/kubernetes-csi/livenessprobe/pull/171
- https://github.com/kubernetes-csi/node-driver-registrar/pull/250
- https://github.com/kubernetes-csi/external-resizer/pull/236
- https://github.com/kubernetes-csi/external-provisioner/pull/823
Change the repo that you need to generate the pr.
Sample command:
```
./go-modules-update.sh -v 1.26.0-rc.0 -u sunnylovestiramisu
```
```release-note
NONE
```

Add wrapper script for sidecar release

---

prow.sh

Kubernetes publishes `.go-version` since v1.26.1. Use it to get Kubernete's go version instead of parsing a shell script. Fall back to parsing of hack/lib/golang.sh if `.go-version` does not exist.
Fixes: https://github.com/kubernetes-csi/csi-release-tools/issues/248
```release-note
Use .go-version file from github.com/kubernetes/kubernetes (k/k) to detect go version that k/k needs.
```

Use .go-version to get Kubernetes go version

---

prow.sh

Update go version to be in sync with Kubernetes 1.30, which uses 1.22.2.
cc @xing-yang @msau42 
```release-note
Go updated to 1.22.2
```

Update go to 1.22.2

---

build.make
verify-logcheck.sh

The new `test-logcheck` + `verify-logcheck.sh` script checks for correct klog usage.
It's optional and must be explicitly requested in the main Makefile by adding:
```
test: test-logcheck
```
```release-note
Added support for structured and contextual logging check
```

Add test-logcheck target

---

prow.sh

Bump Go version to 1.22.3 due to vulnerabilities in Go 1.22.2 identified by the Trivy vulnerability scanner.
https://github.com/kubernetes-csi/livenessprobe/pull/262
https://github.com/kubernetes-csi/livenessprobe/actions/runs/9034677921/job/24827762006?pr=262
```release-note
Go updated to 1.22.3
```

Update go to 1.22.3

---

SIDECAR_RELEASE_PROCESS.md

This is causing the external-provisioner pre merge tests to fail on PR https://github.com/kubernetes-csi/external-provisioner/pull/1218

fix typo in sidecar release process

---

prow.sh

adds CSI_PROW_SIDECAR_E2E_PATH, an alternative to CSI_PROW_SIDECAR_E2E_IMPORT_PATH that can be used if the go module referenced in the import path has a /v{x} suffix, making it differing from the directory of the module.
This allows https://github.com/kubernetes-csi/external-provisioner/pull/1236#issuecomment-2185900044 to be fixed by referencing it explicitly

chore: add CSI_PROW_SIDECAR_E2E_PATH

---

build.make

Always enable race detection while running tests. This is useful for detecting simpler data races in code.
```release-note
Always enable race detection while running tests
```

Always enable race detection while running tests

---

prow.sh

Should prevent go from automatically downloading newer toolchains. And ensure the specified version is used.
BTW, this also enables support for platforms other than linux/amd64
```release-note
Requires at least go1.21 to run prow.sh
```
See also:
- https://go.dev/doc/toolchain
- https://github.com/kubernetes/kubernetes/pull/120279
It works like this:
```
$ go version
go version go1.23.1 darwin/arm64
$ run_with_go "" go version
2024年11月 9日 星期六 00时59分35秒 CST go1.23.1 /Users/huww98/Downloads$ go version
go version go1.23.1 darwin/arm64
$ run_with_go "1.23.0" go version
2024年11月 9日 星期六 00时59分51秒 CST go1.23.0 /Users/huww98/Downloads$ go version
go version go1.23.0 darwin/arm64
$ run_with_go "1.23.2" go version
go: downloading go1.23.2 (darwin/arm64)
2024年11月 9日 星期六 01时01分21秒 CST go1.23.2 …
```

use new GOTOOLCHAIN env to manage go version

---

prow.sh

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
The `--kube-root` flag has been deprecated in kind for some time and will be removed. The current equivalent functionality is to pass the path to the kubernetes source as the first non-flag argument to `build node-image`.
This updates the prow script to use the newer preferred method in preparation for kind dropping the flag.
**Which issue(s) this PR fixes**:
Related: https://github.com/kubernetes-sigs/kind/issues/3717
**Special notes for your reviewer**:
```release-note
NONE
```

Remove --kube-root deprecated kind argument

---

prow.sh

If we don't set this, k/k build script will set GOMODCACHE different from default, and re-download the toolchain (or fail to build for Kubernetes <= 1.29).

Set GOMODCACHE to avoid re-download toolchain

---

cloudbuild.yaml

This is required for the GOTOOLCHAIN env to be effective.
It contains go1.22.5
Fixes: 6b05f0fcc7af6416ed9e83740848c9144f50e90f
Fixes: #262
```release-note
NONE
```

Update cloudbuild image with go 1.21+

---

prow.sh

```
─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │        Fixed Version        │                            Title                             │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-45336 │ MEDIUM   │ fixed  │ v1.23.1           │ 1.22.11, 1.23.5, 1.24.0-rc2 │ golang: net/http: net/http: sensitive headers incorrectly    │
│         │                │          │        │                   │                             │ sent after cross-domain redirect …
```

Bump golang to 1.23.6 to fix CVE-2024-45336, CVE-2025-22866

---

prow.sh

`v0.14.0` can not create a cluster for 1.32. 
```
root@demo-control-plane:/etc/kubernetes/manifests# cat *.yaml | grep image
image: registry.k8s.io/etcd:3.5.16-0
imagePullPolicy: IfNotPresent
image: registry.k8s.io/kube-apiserver:v1.32.0-5_642efbb595df18
imagePullPolicy: IfNotPresent
image: registry.k8s.io/kube-controller-manager:v1.32.0-5_642efbb595df18
imagePullPolicy: IfNotPresent
image: registry.k8s.io/kube-scheduler:v1.32.0-5_642efbb595df18
imagePullPolicy: IfNotPresent
root@demo-control-plane:/etc/kubernetes/manifests# crictl images
IMAGE                                           TAG                        IMAGE ID            SIZE
k8s.gcr.io/pause                                3.6                        7d46a07936af9       254kB
registry.k8s.io/etcd …
```

update default kind version to v0.25.0

---

prow.sh

**Release note**:
```release-note
Bump golang to 1.24.0
```

Bump golang to 1.24.0

---

prow.sh

**Release note**:
```
Bump golang to 1.24.2 to fix CVE-2025-22871
```

Bump golang to 1.24.2 to fix CVE-2025-22871

---

prow.sh

Fix CVE-2025-22874.
https://github.com/kubernetes-csi/csi-release-tools/actions/runs/15940197412/job/44984669077?pr=279

Update to go 1.24.4
